# Generated by Django 6.0.7 on 2026-07-08

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='sr_no',
            field=models.IntegerField(default=0, db_index=True),
        ),
    ]
