# Generated by Django 6.0.7 on 2026-07-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_sr_no_to_billitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billitem',
            options={'ordering': ['sr_no']},
        ),
    ]
